name: Deploy Backend to ECS (Fargate)

on:
  push:
    branches: [ "main" ]
    paths:
      - "audithor_project/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: "759132943136"
  ECR_REPO: "audithor-api"            # nombre del repo en ECR
  ECS_CLUSTER: "audithor-cluster"
  ECS_SERVICE: "audithor-service"
  CONTAINER_NAME: "audithor-api"      # nombre del contenedor dentro de la task definition

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_BACKEND }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # Instalar jq para manipular JSON
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Construir & subir imagen
      - name: Build, tag and push image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -e
          IMAGE_URI="$ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG"
          IMAGE_URI_LATEST="$ECR_REGISTRY/${ECR_REPO}:latest"

          # Ajusta --platform si tu imagen base/target es distinta
          docker build \
            --platform=linux/amd64 \
            -t "$IMAGE_URI" \
            -t "$IMAGE_URI_LATEST" \
            audithor_project

          docker push "$IMAGE_URI"
          docker push "$IMAGE_URI_LATEST"

          echo "IMAGE=$IMAGE_URI" >> $GITHUB_ENV

      # Exportar la task definition usada por el servicio
      - name: Get current task definition
        id: td
        run: |
          set -e
          TD_ARN=$(aws ecs describe-services \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}" \
            --query 'services[0].taskDefinition' \
            --output text)
          echo "Current TD ARN: $TD_ARN"

          aws ecs describe-task-definition \
            --task-definition "$TD_ARN" \
            --query 'taskDefinition' > taskdef.json

          echo "TD_ARN=$TD_ARN" >> $GITHUB_OUTPUT
          jq '.family, .containerDefinitions[] | {name, image}' taskdef.json

      # Registrar nueva revisión reemplazando SOLO la imagen del contenedor objetivo
      - name: Register new task definition revision (with new image)
        id: register
        run: |
          set -e
          jq --arg name "${CONTAINER_NAME}" --arg image "${IMAGE}" \
            ' .containerDefinitions = (.containerDefinitions
                | map(if .name == $name then .image = $image else . end))
            | del(.taskDefinitionArn, .revision, .status, .registeredBy, .registeredAt, .compatibilities)
            ' taskdef.json > new-taskdef.json

          NEW_TD_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "New TD ARN: $NEW_TD_ARN"
          echo "NEW_TD_ARN=$NEW_TD_ARN" >> $GITHUB_OUTPUT

      # Actualizar el servicio a la nueva revisión
      - name: Update service
        run: |
          set -e
          aws ecs update-service \
            --cluster "${ECS_CLUSTER}" \
            --service "${ECS_SERVICE}" \
            --task-definition "${{ steps.register.outputs.NEW_TD_ARN }}" \
            --force-new-deployment

      # Esperar a que se estabilice
      - name: Wait for service stability
        run: |
          aws ecs wait services-stable \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}"
          echo "Deployment completed ✅"
