name: Deploy Backend to ECS (Fargate)

on:
  push:
    branches: [ "main" ]
    paths:
      - "audithor_project/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: "759132943136"
  ECR_REPO: "audithor-api"
  ECS_CLUSTER: "audithor-cluster"
  ECS_SERVICE: "audithor-service"
  CONTAINER_NAME: "audithor-api"
  DOCKER_CONTEXT: "audithor_project"   # 👈 Aquí está tu backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_BACKEND }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Build, tag and push image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          echo "Building Docker image from context: ${DOCKER_CONTEXT}"

          docker build -t "$ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG" "${DOCKER_CONTEXT}"

          docker tag "$ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG" "$ECR_REGISTRY/${ECR_REPO}:latest"
          docker push "$ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/${ECR_REPO}:latest"
          echo "IMAGE=$ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Get current task definition
        id: td
        run: |
          TD_ARN=$(aws ecs describe-services \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}" \
            --query 'services[0].taskDefinition' \
            --output text)
          echo "Current TD ARN: $TD_ARN"

          aws ecs describe-task-definition \
            --task-definition "$TD_ARN" \
            --query 'taskDefinition' > taskdef.json

          echo "TD_ARN=$TD_ARN" >> $GITHUB_OUTPUT

      - name: Register new task definition revision (with new image)
        id: register
        run: |
          NEW_TD=$(jq --arg name "${CONTAINER_NAME}" --arg image "${IMAGE}" \
            ' .containerDefinitions = (.containerDefinitions | map(if .name == $name then .image = $image | . else . end))
            | del(.taskDefinitionArn, .revision, .status, .registeredBy, .registeredAt, .compatibilities)
            ' taskdef.json)

          echo "$NEW_TD" > new-taskdef.json

          NEW_TD_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "New TD ARN: $NEW_TD_ARN"
          echo "NEW_TD_ARN=$NEW_TD_ARN" >> $GITHUB_OUTPUT

      - name: Update service
        run: |
          aws ecs update-service \
            --cluster "${ECS_CLUSTER}" \
            --service "${ECS_SERVICE}" \
            --task-definition "${{ steps.register.outputs.NEW_TD_ARN }}" \
            --force-new-deployment

      - name: Wait for service stability
        run: |
          aws ecs wait services-stable \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}"
